module Absshl where

-- Haskell module generated by the BNF converter


newtype Ident = Ident String deriving (Eq,Ord,Show)
data Prog =
   Program Blk
  deriving (Eq,Ord,Show)

data Blk =
   Block [Dec] [Stm]
  deriving (Eq,Ord,Show)

data Stm =
   ForLoop Ident Exp Blk
 | IfStmt Exp Blk
 | IfElseStmt Exp Blk Blk
 | ReturnStmt Exp
 | PrintStmt Exp
 | ExpStmt Exp
 | Assign Ident Exp
  deriving (Eq,Ord,Show)

data Dec =
   Declaration Typ Ident
 | DeclarationAssing Typ Ident Exp
 | DeclarationFunc Typ Ident [FArg] Blk
  deriving (Eq,Ord,Show)

data FArg =
   FArgument Typ Ident
 | FArgumentAssing Typ Ident Exp
 | FArgumentFunc Typ Ident [FArg]
 | FArgumentRef Typ Ident
  deriving (Eq,Ord,Show)

data Typ =
   TInt
 | TBool
 | TString
  deriving (Eq,Ord,Show)

data Exp =
   Eeq Exp Exp
 | Eneq Exp Exp
 | Elthen Exp Exp
 | Egrthen Exp Exp
 | Ele Exp Exp
 | Ege Exp Exp
 | Eplus Exp Exp
 | Eminus Exp Exp
 | Etimes Exp Exp
 | Ediv Exp Exp
 | Einc Ident
 | Edec Ident
 | Einvok Ident [IParam]
 | Evar Ident
 | Econst Constraint
  deriving (Eq,Ord,Show)

data Constraint =
   Eint Integer
 | Ebool BoolT
 | Estring String
  deriving (Eq,Ord,Show)

data BoolT =
   Constraint_True
 | Constraint_False
  deriving (Eq,Ord,Show)

data IParam =
   InvokeParamater Exp
  deriving (Eq,Ord,Show)

